name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Free disk space
      run: |
        df -h
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt-get remove powershell google-chrome-stable google-cloud-sdk firefox
        sudo apt clean
        sudo apt-get autoremove --purge
        docker image ls -a
        docker images | grep -v $'docker\|minute\|alpine\azure' | grep -v "none"
        docker rmi $(docker images | grep -v $'docker\|minute\|alpine\|azure' | grep -v "none" | awk '{print $3}')
        docker image ls -a
        docker container ls -a
        df -h
    - name: Build and publish on Dockerhub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: matmu/vep
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        dockerfile: Docker.99-GRCh38
        tags: "latest,99-GRCh38"
