name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Free disk space
      run: |
        df -h
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt-get remove powershell google-chrome-stable google-cloud-sdk firefox dotnet-sdk-3.1 dotnet-sdk-3.0 hhvm zulu-11-azure-jdk zulu-12-azure-jdk azure-cli
        sudo apt clean
        sudo apt-get autoremove --purge
        docker image ls -a
        docker rmi $(docker images | grep " \(hours\|weeks\|years\) ago\|<none>\|jekyll\|azure\|docker" | awk '{print $3}')
        docker image ls -a
        docker container ls -a
        df -h
    - name: Build and publish on Dockerhub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: matmu/vep
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        dockerfile: Docker.99-GRCh38
        tags: "latest,99-GRCh38"
