name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Free disk space
      run: |
        df -h
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        sudo apt-get autoremove --purge
        dpkg-query -W --showformat='${Installed-Size;10}\t${Package}\n' | sort -k1,1n
        df -h
    - name: Build and publish on Dockerhub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: matmu/vep
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        dockerfile: Docker.99-GRCh38
        tags: "latest,99-GRCh38"
