name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Free disk space
      run: |
        df -h
        dpkg-query -Wf '${Package;-40}${Priority}\n' | sort -b -k2,2 -k1,1
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt-get remove powershell google-chrome-stable google-cloud-sdk firefox
        sudo apt clean
        sudo apt-get autoremove --purge
        docker rmi $(docker images | grep " [weeks|weeks]* ago" | awk '{print $3}')
        df -h
    - name: Build and publish on Dockerhub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: matmu/vep
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        dockerfile: Docker.99-GRCh38
        tags: "latest,99-GRCh38"
