name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Free disk space
      run: |
        df -h
        dpkg-query -Wf '${Package;-40}${Priority}\n' | sort -b -k2,2 -k1,1
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt-get remove powershell zulu-7-azure-jdk llvm-6.0-dev moby-engine dotnet-sdk-3.1 dotnet-sdk-3.0 llvm-9-dev llvm-8-dev firefox zulu-8-azure-jdk google-chrome-stable google-cloud-sdk hhvm zulu-11-azure-jdk zulu-12-azure-jdk azure-cli ghc-8.0.2 ghc-8.2.2 ghc-8.4.4 ghc-8.6.2 ghc-8.6.3 ghc-8.6.4 ghc-8.6.5
        sudo apt clean
        sudo apt-get autoremove --purge
        #dpkg-query -W --showformat='${Installed-Size;10}\t${Package}\n' | sort -k1,1n
        docker image ls -a
        df -h
    - name: Build and publish on Dockerhub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: matmu/vep
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        dockerfile: Docker.99-GRCh38
        tags: "latest,99-GRCh38"
