name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Free disk space
      run: |
        df -h
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        sudo apt-get autoremove --purge
        docker rmi $(docker image ls -aq)
        df -h
    - name: Build and publish the Docker image
      run: |
      docker build . --file Docker.99-GRCh37 --tag matmu/vep:99-GRCh37
